'use client'
import { useState } from 'react'
import Link from 'next/link'
import { qualify, type Answers } from '@/lib/qualification'

const defaults:Answers={offer:'',size:'',budget:'',timing:'',sponsor:'',readiness:'',problem:''}
export function Diagnostic({ initialOffer='' }: { initialOffer?:string }) {
  const [answers,setAnswers]=useState<Answers>({...defaults,offer:['ai','product'].includes(initialOffer)?initialOffer:''})
  const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false)
  const update=(name:keyof Answers,value:string)=>setAnswers({...answers,[name]:value})
  const select=(name:keyof Answers,label:string,options:[string,string][])=> <label>{label}<select required value={answers[name]} onChange={e=>update(name,e.target.value)}><option value="">Sélectionner…</option>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>
  const result=qualify(answers)
  async function submit(e:React.FormEvent<HTMLFormElement>) {
    e.preventDefault();setError('')
    if(step<2){setStep(step+1);return}
    const data=new FormData(e.currentTarget);setBusy(true)
    try{const response=await fetch('/api/diagnostic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers,name:data.get('name'),email:data.get('email'),company:data.get('company'),consent:data.get('consent')==='on',website:data.get('website'),source:new URLSearchParams(window.location.search).get('utm_source')?.slice(0,100)||'direct'})});if(!response.ok)throw new Error('Votre demande n’a pas pu être enregistrée. Veuillez réessayer.');setDone(true)}catch(e){setError(e instanceof Error?e.message:'Une erreur est survenue.')}finally{setBusy(false)}
  }
  if(done)return <div className="m-form" role="status"><p className="m-eyebrow">Demande enregistrée</p><h2>Un premier cap pour votre projet.</h2><div className="m-result"><strong>{result.route==='meeting' ? (answers.offer==='ai'?'AI Operations':'Product Launch') : result.route==='blueprint'?'Commençons par un Blueprint':'Clarifions votre périmètre'}</strong><p>{result.route==='meeting'?'Votre contexte semble adapté à un échange de cadrage. Nous confirmerons ensemble le périmètre et les conditions de réalisation.':result.route==='blueprint'?'Un cadrage permettra de préciser les inconnues avant de vous engager dans la réalisation. Blueprint : 4 900 € HT, 10 jours.':'Votre enveloppe appelle un périmètre plus ciblé. Nous examinerons votre demande pour vous proposer une orientation adaptée.'}</p></div><p className="m-note">Votre contexte est transmis à l’équipe ByARMS. La recommandation est indicative et sera examinée par un interlocuteur humain.</p>{result.route==='meeting'&&<a className="m-button" style={{marginTop:20}} href="https://calendly.com/armsjonathan878/30min" target="_blank" rel="noopener noreferrer">Réserver mon échange ↗</a>}<Link className="m-text-link" style={{display:'block',marginTop:25}} href="/">Revenir à l’accueil</Link></div>
  return <form className="m-form" onSubmit={submit}><p className="m-eyebrow">Étape {step+1} sur 3 · environ 3 minutes</p><div className="m-progress" aria-hidden="true">{[0,1,2].map(n=><span className={n<=step?'active':''} key={n}/>)}</div><h2>{['Votre ambition','Votre contexte','Préparons la suite'][step]}</h2>{step===0&&<>{select('offer','Quel changement souhaitez-vous créer ?',[['product','Lancer ou moderniser un produit'],['ai','Automatiser un processus'],['unsure','Clarifier la bonne direction']])}<label>{answers.offer==='ai'?'Quel processus mobilise vos équipes ?':'Quel problème voulez-vous résoudre ?'}<textarea required minLength={20} maxLength={3000} value={answers.problem} onChange={e=>update('problem',e.target.value)} placeholder="Décrivez la situation actuelle, ses conséquences et le résultat attendu…"/></label>{select('size','Votre organisation',[['small','Moins de 20 collaborateurs'],['20-250','20 à 250 collaborateurs'],['large','Plus de 250 collaborateurs'],['funded','Startup financée']])}</>}{step===1&&<>{select('budget','Enveloppe de réalisation envisagée',[['under15','Moins de 15 000 €'],['15-25','15 000 à 25 000 €'],['25-50','25 000 à 50 000 €'],['50plus','Plus de 50 000 €'],['unknown','À définir']])}{select('timing','Quand souhaitez-vous prendre une décision ?',[['30','Dans les 30 jours'],['90','Dans les 90 jours'],['later','Plus tard / en exploration']])}{select('sponsor','Un décideur est-il impliqué ?',[['yes','Oui'],['no','Pas encore']])}{select('readiness',answers.offer==='ai'?'Données et outils du processus':'Accès aux utilisateurs et besoins prioritaires',[['ready','Disponibles et identifiés'],['partial','Partiellement disponibles'],['unknown','À clarifier']])}</>}{step===2&&<><label>Nom complet<input name="name" autoComplete="name" required maxLength={120}/></label><label>Email professionnel<input name="email" type="email" autoComplete="email" required maxLength={200}/></label><label>Entreprise<input name="company" autoComplete="organization" required maxLength={160}/></label><label className="m-hidden" aria-hidden="true">Site web<input name="website" tabIndex={-1} autoComplete="off"/></label><label><input name="consent" type="checkbox" required/>J’accepte que ByARMS utilise ces informations pour examiner ma demande et me recontacter. <Link href="/confidentialite" style={{textDecoration:'underline'}}>Confidentialité</Link></label><p className="m-note">N’incluez aucun mot de passe ni document sensible. Ce diagnostic utilise des règles de qualification ; vos réponses ne sont pas envoyées à un modèle IA.</p></>}{error&&<p className="m-error" role="alert">{error}</p>}<div className="m-form-actions">{step>0&&<button type="button" className="m-button m-button-secondary" onClick={()=>{setStep(step-1);setError('')}}>Retour</button>}<button disabled={busy} type="submit" className="m-button">{busy?'Enregistrement…':step===2?'Recevoir mon orientation ↗':'Continuer →'}</button></div></form>
}
