import Link from 'next/link'
import Image from 'next/image'
import { MarketingMotion } from './MarketingMotion'
import type { ReactNode } from 'react'
import { ArrowUpRight, ArrowRight, Check, Layers3, Workflow, ShieldCheck } from 'lucide-react'

export function CTA({ children = 'Évaluer mon projet', href = '/diagnostic', secondary = false }: { children?: ReactNode; href?: string; secondary?: boolean }) {
  return <Link className={`m-button ${secondary ? 'm-button-secondary' : ''}`} href={href}>{children}<ArrowUpRight size={17} /></Link>
}
export function Shell({ children }: { children: ReactNode }) {
  return <MarketingMotion><a className="m-skip" href="#main">Aller au contenu</a><header className="m-header"><Link href="/" className="m-brand" aria-label="ByARMS, accueil"><span className="m-legacy-logo"><Image src="/byarms-logo.png" alt="" fill sizes="58px" priority /></span>ByARMS</Link><nav aria-label="Navigation principale" className="m-nav"><Link href="/product-launch">Product Launch</Link><Link href="/ai-operations">AI Operations</Link><Link href="/ada">L’OS ADA <span className="m-new">OS</span></Link><Link href="/confiance">Notre engagement</Link></nav><CTA /><details className="m-mobile"><summary>Menu</summary><nav aria-label="Navigation mobile"><Link href="/product-launch">Product Launch</Link><Link href="/ai-operations">AI Operations</Link><Link href="/ada">ADA</Link><Link href="/confiance">Notre engagement</Link><Link href="/diagnostic">Évaluer mon projet ↗</Link></nav></details></header><main id="main">{children}</main><footer className="m-footer"><div className="m-footer-top"><Link href="/" className="m-brand" aria-label="ByARMS, accueil"><span className="m-legacy-logo"><Image src="/byarms-logo.png" alt="" fill sizes="58px" /></span>ByARMS</Link><p>Des ambitions claires.<br />Des systèmes opérationnels.</p><div><Link href="/ada">Powered by ADA ↗</Link><a href="https://ada.byarms.com" target="_blank" rel="noopener noreferrer">Documentation ADA ↗</a><Link href="/diagnostic">Évaluer mon projet ↗</Link></div></div><div className="m-footer-bottom"><p>© {new Date().getFullYear()} ARMS INTERNATIONAL LTD · Company number 17382099</p><div><Link href="/mentions-legales">Informations légales</Link><Link href="/confidentialite">Confidentialité</Link></div></div></footer></MarketingMotion>
}
export function Intro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) {
  return <div className="m-intro"><p className="m-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="m-lead">{text}</p></div>
}
export const steps = [
  ['01', 'Comprendre avant de construire', 'Un problème explicite, un parcours prioritaire et des critères de réussite partagés.'],
  ['02', 'Concevoir avec ADA', 'Claude Code et Codex, une mémoire projet et des contrôles d’exécution réunis dans notre AI Engineering OS.'],
  ['03', 'Valider à chaque jalon', 'Des démonstrations régulières, des décisions tracées et des validations à chaque jalon.'],
  ['04', 'Livrer et transmettre', 'Un système opérationnel, son code, sa documentation et les clés pour le faire évoluer.'],
]
export function Method() { return <section className="m-section"><div className="m-section-head"><div><p className="m-eyebrow">Une méthode, du premier échange à la production</p><h2>Une direction claire.<br />À chaque étape.</h2></div><p>La technologie accélère le travail.<br />Notre équipe porte les décisions.</p></div><div className="m-steps">{steps.map(([n,t,d]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section> }
export function BottomCTA() { return <section className="m-closing"><p className="m-eyebrow">Le premier pas est une conversation bien préparée</p><h2>Quel projet mérite<br />votre investissement<span> ?</span></h2><CTA /><p>Trois minutes pour présenter votre contexte et obtenir une première orientation. Sans engagement.</p></section> }
export function Offers() { return <section className="m-section" id="offres"><div className="m-section-head"><div><p className="m-eyebrow">Deux ambitions. Deux points de départ.</p><h2>Quel changement<br />voulez-vous créer ?</h2></div><p>Un périmètre défini. Un prix convenu.<br />Un résultat que l’on peut montrer.</p></div><div className="m-offers"><Link href="/product-launch" className="m-offer"><div className="m-offer-top"><Layers3 /><span>01 / CRÉER UN ACTIF NUMÉRIQUE</span><ArrowUpRight /></div><h3>Product Launch</h3><p>Vous avez un produit à lancer ou un outil métier à moderniser. Nous livrons une première version centrée sur le parcours utilisateur prioritaire.</p><div className="m-offer-art"><span className="m-mini-window"><i /><i /><i /><b>Votre prochain produit.</b><em>Conçu pour être utilisé.</em></span></div><div className="m-offer-bottom"><span><strong>34 900 € HT</strong> · 10 semaines</span><ArrowRight /></div></Link><Link href="/ai-operations" className="m-offer m-offer-blue"><div className="m-offer-top"><Workflow /><span>02 / TRANSFORMER VOS OPÉRATIONS</span><ArrowUpRight /></div><h3>AI Operations</h3><p>Les ressaisies et traitements répétitifs mobilisent vos équipes. Nous construisons une automatisation connectée à vos outils, évaluée sur votre processus.</p><div className="m-workflow-art" aria-hidden="true"><span>Vos données</span><i>→</i><b>IA métier</b><i>→</i><span>Action validée</span></div><div className="m-offer-bottom"><span><strong>29 900 € HT</strong> · 8 semaines</span><ArrowRight /></div></Link></div><p className="m-note">Chaque réalisation peut commencer par un Blueprint : cadrage et décision go/no-go en 10 jours, à 4 900 € HT. Délais et prix selon le périmètre convenu.</p></section> }
export function AdaPanel() { return <div className="m-system"><div className="m-system-label"><span><i /> BYARMS ENGINEERING SYSTEM</span><span>01 — 03</span></div><div className="m-system-core"><span>POWERED BY</span><strong>ADA<span>↗</span></strong><p>AI Engineering OS multi-engine</p></div><div className="m-system-rows">{[['01','Moteurs','Claude Code · Codex'],['02','Contexte','Mémoire projet & agents'],['03','Exécution','Permissions & suivi']].map(([n,t,d]) => <div key={n}><span>{n}</span><b>{t}</b><small>{d}</small><Check size={15}/></div>)}</div><div className="m-human"><ShieldCheck size={18}/><span>Supervision humaine à chaque décision clé</span></div></div> }
