'use client'
import { useState } from 'react'
import { CTA } from './Marketing'
export function ValueCalculator() {
  const [volume,setVolume]=useState(1500),[minutes,setMinutes]=useState(12),[hourly,setHourly]=useState(35),[gain,setGain]=useState(30),[monthly,setMonthly]=useState(200)
  const annual=volume*minutes/60*hourly*12, saved=annual*gain/100, net=saved-monthly*12
  const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)
  return <div className="m-detail-grid"><div><p className="m-eyebrow">Calculateur de valeur</p><h2>Que vous coûte<br/>le travail répétitif ?</h2><p className="m-lead" style={{marginTop:22}}>Explorez une hypothèse de gain de capacité. Ajustez les paramètres à votre réalité.</p><div className="m-result" aria-live="polite"><p>Coût annuel du temps mobilisé</p><strong>{money(annual)}</strong><p>Valeur annuelle du temps libéré, avant coûts récurrents</p><strong>{money(saved)}</strong><p>Après {money(monthly)} de coûts mensuels estimés : {money(net)} / an.<br/>{net>0 ? `Retour indicatif sur 29 900 € : ${(29900/(net/12)).toFixed(1).replace('.',',')} mois.` : 'Pas de retour positif avec ces hypothèses.'}</p></div><p className="m-note">Le temps libéré n’est pas automatiquement une économie de trésorerie. Estimation hors coûts de changement, formation et montée en charge. Aucun gain garanti ; baseline à confirmer pendant le Blueprint.</p></div><div className="m-form" style={{width:'100%'}}>{[{label:'Opérations par mois',value:volume,set:setVolume,min:1,max:100000},{label:'Minutes par opération',value:minutes,set:setMinutes,min:1,max:480},{label:'Coût horaire chargé (€)',value:hourly,set:setHourly,min:1,max:500},{label:'Coûts récurrents mensuels estimés (€)',value:monthly,set:setMonthly,min:0,max:100000}].map(f=><label key={f.label}>{f.label}<input type="number" min={f.min} max={f.max} value={f.value} onChange={e=>f.set(Math.min(f.max,Math.max(f.min,Number(e.target.value)||f.min)))}/></label>)}<label>Hypothèse de temps libéré : {gain} %<input type="range" min="5" max="80" step="5" value={gain} onChange={e=>setGain(Number(e.target.value))}/></label><CTA href="/diagnostic?offre=ai">Étudier mon processus</CTA></div></div>
}
