import type { Metadata } from 'next'
import Link from 'next/link'
import { Shell, Intro } from '@/components/Marketing'
import { Diagnostic } from '@/components/Diagnostic'
import { JsonLd } from '@/components/JsonLd'
import { pageGraph } from '@/lib/schema'
export const metadata: Metadata = {
  title: 'Évaluer mon projet : orientation en 3 minutes',
  description: 'Décrivez votre projet logiciel ou IA en 3 minutes : budget, priorités, échéance. Première orientation, réponse de l’équipe, sans engagement.',
  alternates: { canonical: '/diagnostic' },
  openGraph: { url: '/diagnostic', images: '/opengraph-image', title: 'Évaluer mon projet : orientation en 3 minutes' },
}
export default async function Page({searchParams}:{searchParams:Promise<{offre?:string}>}) { const {offre}=await searchParams;return <Shell><JsonLd data={pageGraph([{ name: 'Évaluer mon projet', path: '/diagnostic' }])} /><Intro eyebrow="Un premier pas concret" title="Votre projet mérite un cadre clair." text="Trois minutes pour présenter votre enjeu, votre budget et vos priorités. Vous obtenez une première orientation, puis notre équipe examine votre demande. Sans engagement."/><section className="m-section" style={{paddingTop:25}}><Diagnostic initialOffer={offre}/></section><section className="m-section" style={{paddingTop:0}}><div className="m-section-head"><div><p className="m-eyebrow">Après l’envoi</p><h2>Ce qui se passe une fois votre demande envoyée</h2></div><p>Trois étapes, sans engagement de votre part.</p></div><div className="m-steps">{[['01','Une première orientation immédiate','À la fin du formulaire, une règle de qualification vous propose une orientation indicative : Product Launch, AI Operations ou un Blueprint de cadrage. Aucun modèle d’IA ne traite vos réponses.'],['02','Un examen par notre équipe','Votre demande est enregistrée et lue par l’équipe ByARMS, qui vous répond par email avec ses questions ou une proposition de cadrage.'],['03','Un rendez-vous si le projet est qualifié','Lorsque la demande est suffisamment précise, nous vous proposons un créneau d’échange pour préciser le périmètre et le budget avant toute proposition.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="m-faq" style={{marginTop:32}}><details><summary>Cette demande m’engage-t-elle ?</summary><p>Non. Le diagnostic sert à orienter l’échange. Aucune proposition, aucun prix et aucun calendrier ne sont engagés avant un cadrage validé par écrit.</p></details><details><summary>Quels documents dois-je fournir ?</summary><p>Aucun. Le formulaire ne demande ni document ni donnée sensible. Si un cadrage nécessite des éléments, nous les listons ensemble après le premier échange.</p></details><details><summary>Qui lit ma demande et comment sont utilisées mes informations ?</summary><p>L’équipe ByARMS, pour examiner votre projet et vous recontacter. Les informations sont conservées dans notre outil de suivi commercial, comme décrit dans notre <Link href="/confidentialite">politique de confidentialité</Link>.</p></details></div></section></Shell> }
